// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttL5pmlBkGBTJvEKvdf0npSvDpxvb9wU',
    appId: '1:362128755185:web:6a7cb48b4cfeea38fd5c50',
    messagingSenderId: '362128755185',
    projectId: 'news-c8',
    authDomain: 'news-c8.firebaseapp.com',
    storageBucket: 'news-c8.appspot.com',
    measurementId: 'G-R49TJFVW9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4liphf-sf6him6MpIgbNE2Dnk0Gaprfg',
    appId: '1:362128755185:android:1068a05ebb875f3ffd5c50',
    messagingSenderId: '362128755185',
    projectId: 'news-c8',
    storageBucket: 'news-c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr9NJtj7Ir2xkl-1Ss1hinqfgoUuGE7pI',
    appId: '1:362128755185:ios:01345687fd075f3cfd5c50',
    messagingSenderId: '362128755185',
    projectId: 'news-c8',
    storageBucket: 'news-c8.appspot.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr9NJtj7Ir2xkl-1Ss1hinqfgoUuGE7pI',
    appId: '1:362128755185:ios:01345687fd075f3cfd5c50',
    messagingSenderId: '362128755185',
    projectId: 'news-c8',
    storageBucket: 'news-c8.appspot.com',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDttL5pmlBkGBTJvEKvdf0npSvDpxvb9wU',
    appId: '1:362128755185:web:69deee98e503b9f7fd5c50',
    messagingSenderId: '362128755185',
    projectId: 'news-c8',
    authDomain: 'news-c8.firebaseapp.com',
    storageBucket: 'news-c8.appspot.com',
    measurementId: 'G-JKL99EMQP7',
  );

}